config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  namespace :sms_login do
    namespace :sessions do
      post :lookup_cellphone_number, as: 'lookup'
      get :sign_in
      delete :sign_out_from_sms_login, as: 'sign_out'
    end
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sms_sender.rb
class SmsSender
  class << self
    def send_message(phone, message)
      return unless ENV['key'] = 'true'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sms_login/sessions_controller.rb
require 'sms_login_handler.rb'
require 'sms_login.rb'

class SmsLogin::SessionsController < ApplicationController
  include SmsLogin::SmsLoginHandler
  
  def sign_in
    if sign_in_with_sms_login_token
      render plain: "로그인에 성공했습니다."
    else
      render plain: "로그인에 실패!"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleSmsLoginApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= simple_form_for(:user, url: sms_login_sessions_lookup_path) do |f| %>
  <div class="form-group">
    <%= f.input "phone_number", label: "핸드폰 번호" %>
    <%= f.button :submit, "핸드폰 번호로 로그인", class: 'btn btn-default' %>
  </div>
<% end %>